/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArnAlerta: typeof import('./src/components/ArnAlerta.vue')['default']
    ArnButton: typeof import('./src/components/buttons/ArnButton.vue')['default']
    ArnCard: typeof import('./src/components/cards/ArnCard.vue')['default']
    ArnDatePicker: typeof import('./src/components/pickers/ArnDatePicker.vue')['default']
    ArnIcon: typeof import('./src/components/ArnIcon.vue')['default']
    ArnLoader: typeof import('./src/components/ArnLoader.vue')['default']
    ArnMatchDetailsModal: typeof import('./src/components/modals/ArnMatchDetailsModal.vue')['default']
    ArnTimePicker: typeof import('./src/components/pickers/ArnTimePicker.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
