/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArenaAlerta: typeof import('./src/components/ArnAlerta.vue')['default']
    ArnAlerta: typeof import('./src/components/ArnAlerta.vue')['default']
    ArnButton: typeof import('./src/components/buttons/ArnButton.vue')['default']
    ArnCard: typeof import('./src/components/cards/ArnCard.vue')['default']
    ArnIcon: typeof import('./src/components/ArnIcon.vue')['default']
    Card: typeof import('./src/components/cards/Card.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
