/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/calendario/': RouteRecordInfo<'/calendario/', '/calendario', Record<never, never>, Record<never, never>>,
    '/calendario/PartidaModal': RouteRecordInfo<'/calendario/PartidaModal', '/calendario/PartidaModal', Record<never, never>, Record<never, never>>,
    '/home/': RouteRecordInfo<'/home/', '/home', Record<never, never>, Record<never, never>>,
    '/home/Historico': RouteRecordInfo<'/home/Historico', '/home/Historico', Record<never, never>, Record<never, never>>,
    '/home/ProximasPartidas': RouteRecordInfo<'/home/ProximasPartidas', '/home/ProximasPartidas', Record<never, never>, Record<never, never>>,
    '/home/Solicitacoes': RouteRecordInfo<'/home/Solicitacoes', '/home/Solicitacoes', Record<never, never>, Record<never, never>>,
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>>,
    '/login/Redirect': RouteRecordInfo<'/login/Redirect', '/login/Redirect', Record<never, never>, Record<never, never>>,
    '/partidas/': RouteRecordInfo<'/partidas/', '/partidas', Record<never, never>, Record<never, never>>,
    '/partidas/CriarPartidas': RouteRecordInfo<'/partidas/CriarPartidas', '/partidas/CriarPartidas', Record<never, never>, Record<never, never>>,
    '/partidas/ProcurarPartidas': RouteRecordInfo<'/partidas/ProcurarPartidas', '/partidas/ProcurarPartidas', Record<never, never>, Record<never, never>>,
  }
}
